export const TypologyEnum = {
    TYPOLOGY_GENERIC: 'TYPOLOGY_GENERIC',
    TYPOLOGY_FRESH: 'TYPOLOGY_FRESH',
    TYPOLOGY_FROZEN: 'TYPOLOGY_FROZEN',
    TYPOLOGY_DANGEROUS: 'TYPOLOGY_DANGEROUS',
    TYPOLOGY_VOLUMINOUS: 'TYPOLOGY_VOLUMINOUS',
    TYPOLOGY_FRAGILE: 'TYPOLOGY_FRAGILE',
    TYPOLOGY_VOLUMINOUS_FRAGILE: 'TYPOLOGY_VOLUMINOUS_FRAGILE'
};
